version: '2'
services:
  web:
    build: .
    command: npm run start-dev
    volumes:
      - .:/usr/workspace/ncms
      - /usr/workspace/ncms/node_modules
    ports:
      - "5000:5000"
    depends_on:
      - postgres
    environment:
      DATABASE_URL: postgres://ncms@postgres/todos
  postgres:
    image: postgres:9.6.2-alpine
    environment:
      POSTGRES_USER: ncms
      POSTGRES_DB: ncms